services:
  db:
    image: postgres:16-alpine
    container_name: frellomanager_db
    environment:
      POSTGRES_DB: FrelloManagerDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: frellomanager_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/FrelloManagerDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  db_data: